### ISSUE TITLE
'Not provided'

### ISSUE THREAD

**Issue by jade-mc** [w3c/wai-authoring-tools-list#121]
Is 'not provided' the default if something isn't provided? This might be off putting for those vendors who aren't as far along in their journey. 
The reason 'not provided' is there is because we want to be transparent and this might be somethign to work towards eventually. But while the list is new and starting out, it might be more of an incentive for the vendor to be able to hide 'not provided'.

**Comment by shawna-slh** [comment]
[9 December 2022 minutes](https://www.w3.org/2022/12/09-eo-minutes#item03)

One of the options was to put the Yes items before the details expand. However, that could be very long.

Instead I tried putting the Accessibility statement link before the details. That will be useful to many list users.

**Comment by shawna-slh** [comment]
OK, it turns out that all of the "not provided"s in the draft we looked at on 9 December was not realistic, just there from a quick test submission.

I went through the submission form with hat on of a real authoring tool vendor -- even one just starting on their accessibility journey -- and I think most will answer most of the questions, even if with 'Partially', 'Not applicable', or 'Not sure'. And if they leave something blank, we do indeed need to be transparent about that.

Check out more realistic example tool listings updated in: https://www.w3.org/WAI/tools-list/authoring/

I'm closing this issue for now. Feel free to re-open.
