### ISSUE TITLE
Make tools listing section wider

### ISSUE THREAD

**Issue by vmmiller** [w3c/wai-authoring-tools-list#20]
Now that the Filters have been moved over (good use of space), I think the section on details could be expanded over one grid to the right.  There is currently too much space on the right.

**Comment by hidde** [comment]
I've slightly rephrased your issue title, to mean the details section should take up more space on the right. (but they where it is on the left). Please let me know if I'm reinterpreting there. 

For context: I'm assuming text should be somewhere between 45-80 characters for readability. 

* Robert Bringhurst: 45-75 (see [The Elements of Typographic Style Applied to the Web, 2.1.2](http://webtypography.net/2.1.2)
* Mark Boulton: 52-78 (see [Measuring the measure](https://markboulton.co.uk/journal/five-simple-steps-to-better-typography/))

In the current design, we're at almost 90, which is wider than advised, I would advise against going even wider.

This is the current situation: 

<img width="1463" alt="authoring tools list screenshot with grid overlayed, showing of 8 columns, the first seven are used" src="https://user-images.githubusercontent.com/178782/66830844-b8e8c800-ef56-11e9-9422-2bc83b055787.png">

It would be possible to move the tools list to the right with one column, but that leaves a gap between filters and content:

<img width="1462" alt="authoring tools list screenshot with grid overlayed, showing 8 columns, with one column left empty between filters and tool listings" src="https://user-images.githubusercontent.com/178782/66830962-f51c2880-ef56-11e9-818e-892692b0a2c7.png">

Note: I left that gap on the left before, so that there was whitespace on the left, but there seemed EOWG consensus that that was not preferred.

**Comment by vmmiller** [comment]
Hi, Hidde,

No, I meant it stayed in the "new" position but spanned over an additional
column.  Perhaps, leave as you originally had moved it and see if others
feel the same or not.

Cheer,s

Vicki

**Comment by hidde** [comment]
Hi Vicki,

Thanks for the clarification. Did you mean something like this: 

<img width="1478" alt="Screenshot with grid overlay where tools column spans full width of grid, 6 columns in total" src="https://user-images.githubusercontent.com/178782/66831868-f64e5500-ef58-11e9-8c2a-49a03821ee9b.png">

(With my designer hat on, I think this would makes the tool listing too wide; with my editor hat on: I'm leaving the screenshot here to hear your and other people's feedback on this)

**Comment by vmmiller** [comment]
Yup, that's what I meant. But I do understand your feeling.

**Comment by slhenry** [comment]
Personally I strongly prefer for content to use full width and let me choose to make the line width shorter if I want. Yet I know many users don't adjust the window width or zoom or use large text. I won't get into that broader issue for now.

One thing is un-debate-able (I think ;-): At least the section with the two columns must be wider. In my main configuration, I'm getting terrible text wrapping there. (I can add a screen capture here later.)

**Comment by yatil** [comment]
Well, if the section for the “two columns must be wider”, it will produce the [second screenshot in Hidde’s comment](https://github.com/w3c/wai-authoring-tools/issues/20#issuecomment-542184856) because there is no space left then for widening the details column anyway.

I feel that a big gap will be an issue for zoom users and look awkward for most people. I like how readable this is. Having shorter line length just makes it less a wall of text. (Note: Initially we never planned to have the content as wide as we have now in the main site – we planned for a right gutter for additional information instead.)

**Comment by hidde** [comment]
Please add a screen capture, happy to make your text wrapping less terrible, we need this to work across all viewports including yours.

**Comment by hidde** [comment]
@slhenry I've provided some research regarding text width / 'leading' above, and additionally, following your comment, looked for research countering my points, but did not find any.

As you say, we don't know how many people will adjust their window widths, but what we do know is that some devices don't allow for it (like tablets). This is an additional reason to set line length to some ideal number (or in our case, some flexible with a maximum).

The lay-out, including how it responds to smaller (or zoomed in) viewports., has had some updates since your last comment. I believe it now works well across viewports / zoom levels. 

Does the problem still persist for you? And could you please respond before Monday 18 November?

**Comment by slhenry** [comment]
I apologize that I will not be able to comment by Monday.

**Comment by hidde** [comment]
@slhenry If you agree with the resolution, let's close this issue. 

If not, do you know when you will be able to comment? It would be helpful in moving the project forward.

**Comment by shawna-slh** [comment]
shawna-slh didn't have time to work on this point.
