### ISSUE TITLE
visual design and text sizes

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-authoring-tools-list#41]
The different text sizes bother me. I spent some time trying to figure out why and provide suggestions. I looked around the rest of the WAI site content & CSS for other places where the main content uses different text sizes. (I think only a couple and not primary text - except other tools list) I also looked at the QuickRef and the Eval Tools list.

I was actually a bit surprised to see that the Eval Tools list uses different text sizes. (granted, I rarely go there) They don't bother me there. I think it's because:
* the borders and colors and layout make them clearly different
* the overall layout is different enough that I'm not as bothered that the first text that I read and use (top and left) is smaller than the main WAI site text

Right now I don't have specific suggestions. I do think it needs more visual design work.

Related issue: https://github.com/w3c/wai-authoring-tools/issues/17

**Comment by hidde** [comment]
We have discussed this in EOWG, where I suggested to improve visual distinction between the filters (which has a smaller font size, to reflect it is lower in hierarchy) and the tools list (which has the regular font size, to reflect that it is regular in hierarchy).

I have done this by putting a border between filters and the tools list, so that it is clearer that these are distinct parts of the page, that can have a distinct place in the visual hierarchy.

The same border has been added on smaller viewports, but vertically.

Screenshot smaller viewports with horizontal border between filters and tools:

<img width="541" alt="" src="https://user-images.githubusercontent.com/178782/67375817-7c832080-f583-11e9-8319-975b32e48f9b.png">

Screenshot larger viewports, with vertical border between filters and tools:

<img width="942" alt="" src="https://user-images.githubusercontent.com/178782/67375907-945aa480-f583-11e9-9873-2b66186861cb.png">

**Comment by hidde** [comment]
@slhenry could you please indicate if this problem still persists for you, given that:

* the size difference already existed in other WAI lists
* the two areas are now nicely separated with a vertical line 

If not, I'd like to close the issue.

**Comment by shawna-slh** [comment]
Will go with the decisions of EOWG for https://www.w3.org/WAI/courses/list/
