### ISSUE TITLE
consider for types of tools: SVG tools and captions/subtitle tools

### ISSUE THREAD

**Issue by shawna-slh** [w3c/wai-authoring-tools-list#71]
Consider including category and filter for SVG.

[motivation e-mail ](https://lists.w3.org/Archives/Public/public-svga11y/2021Aug/0001.html) from @chaals

**Comment by shawna-slh** [comment]
Consider including category and filter for captions/subtitles.

https://github.com/w3c/wai-media-guide/issues/181 from @californiakat

**Comment by nitedog** [comment]
We had not considered this type of detail in the initial [requirements analysis](https://github.com/w3c/wai-authoring-tools/wiki/Requirements-Analysis:-Authoring-Tools-List). We had agreed on the core data being the ATAG requirements, with some additional metadata on things like type of tool, licensing, and such. Possibly some of this can be partially addressed by the "type of tool" category, for example by defining types of tools for "infographics", "multimedia", or such. Otherwise I fear this may be quite a significant change to the initially envisioned scope.

**Comment by shawna-slh** [comment]
I was thinking type of tools -- tools that create SVG, tools that create captions/subtitles. I think that would be a filter, not outside of what was defined in the requirements analysis?

Not a high priority, though.
